/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment;

import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author rashi
 */
public class AdminInterface2 extends javax.swing.JFrame implements LogOut {

    /**
     * Creates new form AdminInterface2*/
        public AdminInterface2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registered_users_table = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        Registered_records = new javax.swing.JTable();
        Appointments_View_Table = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        Appointments_View = new javax.swing.JTable();
        Specific_Appointment_Table = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        Specific_appointment = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        Transactions_View_Table = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        Transactions_View = new javax.swing.JTable();
        Specific_Transac_Table = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        Specific_transac = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        Transac_Search = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        Registered_users_table.setMinimumSize(new java.awt.Dimension(895, 289));
        Registered_users_table.setResizable(false);

        Registered_records.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        Registered_records.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TP Number", "Password", "Date And Time", "Role", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Registered_records.setMaximumSize(new java.awt.Dimension(532, 234));
        Registered_records.setMinimumSize(new java.awt.Dimension(532, 234));
        Registered_records.setPreferredSize(new java.awt.Dimension(532, 234));
        jScrollPane2.setViewportView(Registered_records);

        javax.swing.GroupLayout Registered_users_tableLayout = new javax.swing.GroupLayout(Registered_users_table.getContentPane());
        Registered_users_table.getContentPane().setLayout(Registered_users_tableLayout);
        Registered_users_tableLayout.setHorizontalGroup(
            Registered_users_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Registered_users_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                .addContainerGap())
        );
        Registered_users_tableLayout.setVerticalGroup(
            Registered_users_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Registered_users_tableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        Appointments_View_Table.setMinimumSize(new java.awt.Dimension(948, 263));
        Appointments_View_Table.setResizable(false);

        Appointments_View.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        Appointments_View.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "TP Number", "Name", "Unique Reference No.", "Contact No.", "Appliance", "Appointment Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Appointments_View.setMaximumSize(new java.awt.Dimension(450, 192));
        Appointments_View.setMinimumSize(new java.awt.Dimension(450, 192));
        jScrollPane3.setViewportView(Appointments_View);

        javax.swing.GroupLayout Appointments_View_TableLayout = new javax.swing.GroupLayout(Appointments_View_Table.getContentPane());
        Appointments_View_Table.getContentPane().setLayout(Appointments_View_TableLayout);
        Appointments_View_TableLayout.setHorizontalGroup(
            Appointments_View_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Appointments_View_TableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                .addContainerGap())
        );
        Appointments_View_TableLayout.setVerticalGroup(
            Appointments_View_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Appointments_View_TableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Specific_Appointment_Table.setMinimumSize(new java.awt.Dimension(911, 277));
        Specific_Appointment_Table.setResizable(false);

        Specific_appointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "TP Number", "Name", "Unique Reference No.", "Contact No.", "Appliance", "Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(Specific_appointment);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel2.setText("Enter the TP Number :");

        Search.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Specific_Appointment_TableLayout = new javax.swing.GroupLayout(Specific_Appointment_Table.getContentPane());
        Specific_Appointment_Table.getContentPane().setLayout(Specific_Appointment_TableLayout);
        Specific_Appointment_TableLayout.setHorizontalGroup(
            Specific_Appointment_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Specific_Appointment_TableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Specific_Appointment_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Specific_Appointment_TableLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Specific_Appointment_TableLayout.setVerticalGroup(
            Specific_Appointment_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Specific_Appointment_TableLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Specific_Appointment_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        Transactions_View_Table.setMinimumSize(new java.awt.Dimension(1257, 271));
        Transactions_View_Table.setResizable(false);

        Transactions_View.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        Transactions_View.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TP Number", "Name", "Unique Reference No.", "Contact No.", "Amount", "Card Type", "Card No.", "Date And Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Transactions_View.setMaximumSize(new java.awt.Dimension(450, 192));
        Transactions_View.setMinimumSize(new java.awt.Dimension(450, 192));
        jScrollPane5.setViewportView(Transactions_View);
        if (Transactions_View.getColumnModel().getColumnCount() > 0) {
            Transactions_View.getColumnModel().getColumn(0).setPreferredWidth(15);
            Transactions_View.getColumnModel().getColumn(1).setPreferredWidth(15);
            Transactions_View.getColumnModel().getColumn(2).setPreferredWidth(15);
            Transactions_View.getColumnModel().getColumn(3).setPreferredWidth(15);
            Transactions_View.getColumnModel().getColumn(4).setPreferredWidth(15);
            Transactions_View.getColumnModel().getColumn(5).setPreferredWidth(15);
            Transactions_View.getColumnModel().getColumn(6).setPreferredWidth(15);
            Transactions_View.getColumnModel().getColumn(7).setPreferredWidth(50);
        }

        javax.swing.GroupLayout Transactions_View_TableLayout = new javax.swing.GroupLayout(Transactions_View_Table.getContentPane());
        Transactions_View_Table.getContentPane().setLayout(Transactions_View_TableLayout);
        Transactions_View_TableLayout.setHorizontalGroup(
            Transactions_View_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Transactions_View_TableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1393, Short.MAX_VALUE)
                .addContainerGap())
        );
        Transactions_View_TableLayout.setVerticalGroup(
            Transactions_View_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Transactions_View_TableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        Specific_Transac_Table.setMinimumSize(new java.awt.Dimension(1032, 297));
        Specific_Transac_Table.setResizable(false);

        Specific_transac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TP No.", "Name", "Unique Reference No.", "Contact No.", "Amount", "Card Type", "Card No.", "Date And Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(Specific_transac);
        if (Specific_transac.getColumnModel().getColumnCount() > 0) {
            Specific_transac.getColumnModel().getColumn(0).setResizable(false);
            Specific_transac.getColumnModel().getColumn(0).setPreferredWidth(15);
            Specific_transac.getColumnModel().getColumn(1).setPreferredWidth(15);
            Specific_transac.getColumnModel().getColumn(2).setPreferredWidth(15);
            Specific_transac.getColumnModel().getColumn(3).setPreferredWidth(15);
            Specific_transac.getColumnModel().getColumn(4).setPreferredWidth(15);
            Specific_transac.getColumnModel().getColumn(5).setPreferredWidth(15);
            Specific_transac.getColumnModel().getColumn(6).setPreferredWidth(15);
            Specific_transac.getColumnModel().getColumn(7).setPreferredWidth(40);
        }

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane7.setViewportView(jTextArea2);

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel3.setText("Enter the TP Number :");

        Transac_Search.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        Transac_Search.setText("Search");
        Transac_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Transac_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Specific_Transac_TableLayout = new javax.swing.GroupLayout(Specific_Transac_Table.getContentPane());
        Specific_Transac_Table.getContentPane().setLayout(Specific_Transac_TableLayout);
        Specific_Transac_TableLayout.setHorizontalGroup(
            Specific_Transac_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Specific_Transac_TableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Specific_Transac_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
                    .addGroup(Specific_Transac_TableLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Transac_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Specific_Transac_TableLayout.setVerticalGroup(
            Specific_Transac_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Specific_Transac_TableLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Specific_Transac_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Transac_Search, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(654, 386));
        setSize(new java.awt.Dimension(0, 0));

        jButton1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton1.setText("View Pending Appointments");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton2.setText("View All Appointments");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton3.setText("View Specific Appointment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setText("Choose One of the Following Options");

        jButton4.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton4.setText("View All Transactions");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton5.setText("View Specific Transaction");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton6.setText("Log Out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton7.setText("View Login Activtiy");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Admin Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void Logout()
    {
        new MainInterface().setVisible(true);
        this.dispose();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Appointments_View_Table.setModal(false); 
        try
            {
                String Appointment;
                Path P_Appointments = Paths.get(".", "Appointments.txt");
                BufferedReader reader = Files.newBufferedReader(P_Appointments);         
                DefaultTableModel View2 = (DefaultTableModel) Appointments_View.getModel();  
                View2.setRowCount(0);        
                while ((Appointment = reader.readLine()) != null) 
                {
                    String[] fields = Appointment.split("[,]");  
                    if (fields[6].equals("Pending"))
                    {
                        View2.addRow(fields);
                    }
                }
                 
            }
            catch (Exception e) 
            {
                System.out.println("Exception");

            }  
            Appointments_View_Table.setModal(true);
            Appointments_View_Table.setLocationRelativeTo(null);
            Appointments_View_Table.setVisible(true);  
       // TODO add your handling code here:
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Appointments_View_Table.setModal(false); 
        try
            {
                String Appointment;
                Path P_Appointments = Paths.get(".", "Appointments.txt");
                BufferedReader reader = Files.newBufferedReader(P_Appointments);
                DefaultTableModel View2 = (DefaultTableModel) Appointments_View.getModel();  
                View2.setRowCount(0);        
                while ((Appointment = reader.readLine()) != null) 
                {
                    String[] fields = Appointment.split("[,]");  
                    View2.addRow(fields);
                }   
            }
            catch (Exception e) 
            {
                System.out.println("Exception");

            }  
            Appointments_View_Table.setModal(true);
            Appointments_View_Table.setLocationRelativeTo(null);
            Appointments_View_Table.setVisible(true);                                            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Transactions_View_Table.setModal(false); 
        try
            {
                String Transactions;
                Path Transac = Paths.get(".", "Transactions.txt");
                BufferedReader reader = Files.newBufferedReader(Transac);         
                DefaultTableModel View2 = (DefaultTableModel) Transactions_View.getModel();  
                View2.setRowCount(0);        
                while ((Transactions = reader.readLine()) != null) 
                {
                    String[] fields = Transactions.split("[,]");  
                    
                    View2.addRow(fields);
                    
                }
                 
            }
            catch (Exception e) 
            {
                System.out.println("Exception");

            }  
            Transactions_View_Table.setModal(true);
            Transactions_View_Table.setLocationRelativeTo(null);
            Transactions_View_Table.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Specific_Transac_Table.setModal(true); 
       Specific_Transac_Table.setLocationRelativeTo(null);
       Specific_Transac_Table.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Logout();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Specific_Appointment_Table.setModal(true); 
       Specific_Appointment_Table.setLocationRelativeTo(null);
       Specific_Appointment_Table.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Registered_users_table.setModal(false); 
        try
            {
                Path Registeration = Paths.get(".", "Login_Activity.txt");
                BufferedReader reader = Files.newBufferedReader(Registeration);         
                DefaultTableModel View1 = (DefaultTableModel) Registered_records.getModel();  
                View1.setRowCount(0);
                String User_Appointments_Array;        
                while ((User_Appointments_Array = reader.readLine()) != null) 
                {
                    String[] fields = User_Appointments_Array.split("[,]");  
                    View1.addRow(fields);
                }
                 
            }
            catch (Exception e) 
            {
                System.out.println("Exception");

            }  
            Registered_users_table.setModal(true);  
            Registered_users_table.setLocationRelativeTo(null);
            Registered_users_table.setVisible(true);  
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
       int found = 0;
        try
        {
            DefaultTableModel model7 = (DefaultTableModel) Specific_appointment.getModel();  
            model7.setRowCount(0);
            if( jTextArea1.getText().equals(""))
            {
                found = 2;
                JOptionPane.showMessageDialog(rootPane, "Please Enter A TP Number");
            }
            else
            {                       
                    String tpno= jTextArea1.getText();
                    Path Pending = Paths.get(".", "Appointments.txt");
                    try (BufferedReader reader = Files.newBufferedReader(Pending);)
                    {   
                        String line;                      
                        while ((line = reader.readLine()) != null)
                        {
                            String[] fields = line.split("[,]");                              
                            if (tpno.equals(fields[0]))
                            {
                                found = 1;
                                model7.addRow(fields);
                                 
                            }
                        }
                    }  
            }
        }
        catch (IOException ex) {}

        if (found == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Record not found.");
        }                                 
            // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void Transac_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Transac_SearchActionPerformed
        int found = 0;
        try
        {
            DefaultTableModel model7 = (DefaultTableModel) Specific_transac.getModel();  
            model7.setRowCount(0);
            if( jTextArea2.getText().equals(""))
            {
                found = 2;
                JOptionPane.showMessageDialog(rootPane, "Please Enter A TP Number");
            }
            else
            {                       
                String IC = jTextArea2.getText();  
                
                Path Transac = Paths.get(".", "Transactions.txt");
                try (BufferedReader reader = Files.newBufferedReader(Transac);)
                {   
                    String line;                      
                    while ((line = reader.readLine()) != null)
                    {
                        String[] fields = line.split("[,]");                              
                        if (IC.equals(fields[0]))
                        {
                            found = 1;
                            model7.addRow(fields);
                        }
                    }
                }
            }
        }
        catch (IOException ex) {}

        if (found == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Record not found.");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_Transac_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInterface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInterface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInterface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInterface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInterface2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Appointments_View;
    private javax.swing.JDialog Appointments_View_Table;
    private javax.swing.JTable Registered_records;
    private javax.swing.JDialog Registered_users_table;
    private javax.swing.JButton Search;
    private javax.swing.JDialog Specific_Appointment_Table;
    private javax.swing.JDialog Specific_Transac_Table;
    private javax.swing.JTable Specific_appointment;
    private javax.swing.JTable Specific_transac;
    private javax.swing.JButton Transac_Search;
    private javax.swing.JTable Transactions_View;
    private javax.swing.JDialog Transactions_View_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

   // private void fileshare() {
        
    //    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    //}
}
